/**
 * Role catalogue and role -> permission matrix.
 *
 * Roles are system-defined (not user-editable) so that permission checks stay
 * auditable and predictable. Role *assignments* are per user, per tenant, and
 * optionally scoped to a single Moodle instance.
 *
 * Deny entries (leading `-`) exist for the Auditor and Viewer roles, where a
 * broad `read` grant must be carved back for sensitive resources.
 */

import type { Permission } from './permissions.js';

export const ROLES = [
  'super_admin',
  'tenant_admin',
  'moodle_admin',
  'academic_coordinator',
  'teacher_manager',
  'help_desk',
  'analyst',
  'auditor',
  'viewer',
] as const;

export type Role = (typeof ROLES)[number];

export interface RoleDefinition {
  readonly key: Role;
  readonly label: string;
  readonly description: string;
  /** Super admin is platform-scoped and not tenant-scoped. */
  readonly platformScoped: boolean;
  /** Roles that can be assigned within a tenant. */
  readonly assignableInTenant: boolean;
}

export const ROLE_DEFINITIONS: Record<Role, RoleDefinition> = {
  super_admin: {
    key: 'super_admin',
    label: 'Super Admin',
    description: 'Platform owner. Full access across every tenant. Restricted to a break-glass account.',
    platformScoped: true,
    assignableInTenant: false,
  },
  tenant_admin: {
    key: 'tenant_admin',
    label: 'Tenant Admin',
    description: 'Owns one tenant: instances, users, roles, settings and audit.',
    platformScoped: false,
    assignableInTenant: true,
  },
  moodle_admin: {
    key: 'moodle_admin',
    label: 'Moodle Admin',
    description: 'Operates Moodle instances: courses, categories, cohorts and Moodle-side configuration.',
    platformScoped: false,
    assignableInTenant: true,
  },
  academic_coordinator: {
    key: 'academic_coordinator',
    label: 'Academic Coordinator',
    description: 'Runs academic periods, templates, course provisioning and approvals.',
    platformScoped: false,
    assignableInTenant: true,
  },
  teacher_manager: {
    key: 'teacher_manager',
    label: 'Teacher Manager',
    description: 'Manages teachers: workloads, assignments, performance and course creation for teachers.',
    platformScoped: false,
    assignableInTenant: true,
  },
  help_desk: {
    key: 'help_desk',
    label: 'Help Desk',
    description: 'Handles incidents, user support requests and read-only academic data.',
    platformScoped: false,
    assignableInTenant: true,
  },
  analyst: {
    key: 'analyst',
    label: 'Analyst',
    description: 'Builds and runs reports, dashboards and analytics. No academic write access.',
    platformScoped: false,
    assignableInTenant: true,
  },
  auditor: {
    key: 'auditor',
    label: 'Auditor',
    description: 'Read-only access to every domain including audit logs. Cannot mutate academic data.',
    platformScoped: false,
    assignableInTenant: true,
  },
  viewer: {
    key: 'viewer',
    label: 'Viewer',
    description: 'Minimal read-only access to academic data. No audit, no secrets.',
    platformScoped: false,
    assignableInTenant: true,
  },
};

export const isRole = (value: string): value is Role =>
  (ROLES as readonly string[]).includes(value);

/** Permissions granted to every authenticated role in a tenant. */
const TENANT_BASELINE = [
  'search.read',
  'notifications.read',
  'notifications.update',
  'moodles.read',
  'analytics.read',
] as const satisfies readonly string[];

/** Super admin: everything in the catalogue. */
const SUPER_ADMIN: readonly Permission[] = [
  'tenants.read',
  'tenants.create',
  'tenants.update',
  'tenants.delete',
  'tenants.manage',
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'users.suspend',
  'users.export',
  'users.manage',
  'roles.read',
  'roles.manage',
  'moodles.read',
  'moodles.create',
  'moodles.update',
  'moodles.delete',
  'moodles.manage',
  'moodles.execute',
  'courses.read',
  'courses.create',
  'courses.update',
  'courses.delete',
  'courses.export',
  'courses.manage',
  'courses.execute',
  'categories.read',
  'categories.create',
  'categories.update',
  'categories.delete',
  'categories.export',
  'categories.manage',
  'enrolments.read',
  'enrolments.create',
  'enrolments.delete',
  'enrolments.execute',
  'enrolments.export',
  'cohorts.read',
  'cohorts.create',
  'cohorts.update',
  'cohorts.delete',
  'cohorts.manage',
  'cohorts.export',
  'groups.read',
  'groups.create',
  'groups.update',
  'groups.delete',
  'groups.manage',
  'groups.export',
  'activities.read',
  'activities.create',
  'activities.update',
  'activities.delete',
  'activities.execute',
  'activities.manage',
  'grades.read',
  'grades.export',
  'completion.read',
  'completion.export',
  'templates.read',
  'templates.create',
  'templates.update',
  'templates.delete',
  'templates.manage',
  'templates.execute',
  'periods.read',
  'periods.create',
  'periods.update',
  'periods.delete',
  'periods.manage',
  'periods.execute',
  'plans.read',
  'plans.create',
  'plans.execute',
  'plans.delete',
  'jobs.read',
  'jobs.execute',
  'jobs.delete',
  'workflows.read',
  'workflows.create',
  'workflows.update',
  'workflows.delete',
  'workflows.execute',
  'workflows.manage',
  'rules.read',
  'rules.create',
  'rules.update',
  'rules.delete',
  'rules.manage',
  'rules.execute',
  'reports.read',
  'reports.create',
  'reports.update',
  'reports.delete',
  'reports.execute',
  'reports.export',
  'dashboards.read',
  'dashboards.create',
  'dashboards.update',
  'dashboards.delete',
  'dashboards.manage',
  'incidents.read',
  'incidents.create',
  'incidents.update',
  'incidents.delete',
  'incidents.manage',
  'audit.read',
  'audit.export',
  'settings.read',
  'settings.update',
  'settings.manage',
  'apiKeys.read',
  'apiKeys.create',
  'apiKeys.delete',
  'apiKeys.manage',
  'integrations.read',
  'integrations.create',
  'integrations.update',
  'integrations.delete',
  'integrations.manage',
  'analytics.read',
  'analytics.export',
  'search.read',
  'notifications.read',
  'notifications.create',
  'notifications.update',
  'notifications.manage',
] as const;

const TENANT_ADMIN: readonly Permission[] = [
  'users.read',
  'users.create',
  'users.update',
  'users.delete',
  'users.suspend',
  'users.export',
  'users.manage',
  'roles.read',
  'roles.manage',
  'moodles.read',
  'moodles.create',
  'moodles.update',
  'moodles.delete',
  'moodles.manage',
  'moodles.execute',
  'courses.read',
  'courses.create',
  'courses.update',
  'courses.delete',
  'courses.export',
  'courses.manage',
  'courses.execute',
  'categories.read',
  'categories.create',
  'categories.update',
  'categories.delete',
  'categories.export',
  'categories.manage',
  'enrolments.read',
  'enrolments.create',
  'enrolments.delete',
  'enrolments.execute',
  'enrolments.export',
  'cohorts.read',
  'cohorts.create',
  'cohorts.update',
  'cohorts.delete',
  'cohorts.manage',
  'cohorts.export',
  'groups.read',
  'groups.create',
  'groups.update',
  'groups.delete',
  'groups.manage',
  'groups.export',
  'activities.read',
  'activities.create',
  'activities.update',
  'activities.delete',
  'activities.execute',
  'activities.manage',
  'grades.read',
  'grades.export',
  'completion.read',
  'completion.export',
  'templates.read',
  'templates.create',
  'templates.update',
  'templates.delete',
  'templates.manage',
  'templates.execute',
  'periods.read',
  'periods.create',
  'periods.update',
  'periods.delete',
  'periods.manage',
  'periods.execute',
  'plans.read',
  'plans.create',
  'plans.execute',
  'plans.delete',
  'jobs.read',
  'jobs.execute',
  'jobs.delete',
  'workflows.read',
  'workflows.create',
  'workflows.update',
  'workflows.delete',
  'workflows.execute',
  'workflows.manage',
  'rules.read',
  'rules.create',
  'rules.update',
  'rules.delete',
  'rules.manage',
  'rules.execute',
  'reports.read',
  'reports.create',
  'reports.update',
  'reports.delete',
  'reports.execute',
  'reports.export',
  'dashboards.read',
  'dashboards.create',
  'dashboards.update',
  'dashboards.delete',
  'dashboards.manage',
  'incidents.read',
  'incidents.create',
  'incidents.update',
  'incidents.delete',
  'incidents.manage',
  'audit.read',
  'audit.export',
  'settings.read',
  'settings.update',
  'settings.manage',
  'apiKeys.read',
  'apiKeys.create',
  'apiKeys.delete',
  'apiKeys.manage',
  'integrations.read',
  'integrations.create',
  'integrations.update',
  'integrations.delete',
  'integrations.manage',
  'analytics.read',
  'analytics.export',
] as const;

const MOODLE_ADMIN: readonly Permission[] = [
  'users.read',
  'users.create',
  'users.update',
  'users.suspend',
  'users.export',
  'moodles.read',
  'moodles.update',
  'moodles.execute',
  'moodles.manage',
  'courses.read',
  'courses.create',
  'courses.update',
  'courses.delete',
  'courses.export',
  'courses.manage',
  'courses.execute',
  'categories.read',
  'categories.create',
  'categories.update',
  'categories.delete',
  'categories.export',
  'categories.manage',
  'enrolments.read',
  'enrolments.create',
  'enrolments.delete',
  'enrolments.execute',
  'enrolments.export',
  'cohorts.read',
  'cohorts.create',
  'cohorts.update',
  'cohorts.delete',
  'cohorts.manage',
  'cohorts.export',
  'groups.read',
  'groups.create',
  'groups.update',
  'groups.delete',
  'groups.manage',
  'groups.export',
  'activities.read',
  'activities.create',
  'activities.update',
  'activities.delete',
  'activities.execute',
  'activities.manage',
  'grades.read',
  'grades.export',
  'completion.read',
  'completion.export',
  'templates.read',
  'plans.read',
  'plans.create',
  'plans.execute',
  'jobs.read',
  'jobs.execute',
  'rules.read',
  'rules.execute',
  'reports.read',
  'reports.execute',
  'reports.export',
  'dashboards.read',
  'incidents.read',
  'incidents.create',
  'incidents.update',
  'incidents.delete',
  'analytics.read',
  'analytics.export',
] as const;

const ACADEMIC_COORDINATOR: readonly Permission[] = [
  'users.read',
  'users.export',
  'moodles.read',
  'courses.read',
  'courses.create',
  'courses.update',
  'courses.export',
  'courses.manage',
  'courses.execute',
  'categories.read',
  'categories.create',
  'categories.update',
  'categories.export',
  'enrolments.read',
  'enrolments.create',
  'enrolments.delete',
  'enrolments.execute',
  'enrolments.export',
  'cohorts.read',
  'cohorts.create',
  'cohorts.update',
  'cohorts.manage',
  'cohorts.export',
  'groups.read',
  'groups.create',
  'groups.update',
  'groups.manage',
  'groups.export',
  'activities.read',
  'activities.create',
  'activities.update',
  'activities.execute',
  'grades.read',
  'grades.export',
  'completion.read',
  'completion.export',
  'templates.read',
  'templates.create',
  'templates.update',
  'templates.manage',
  'templates.execute',
  'periods.read',
  'periods.create',
  'periods.update',
  'periods.manage',
  'periods.execute',
  'plans.read',
  'plans.create',
  'plans.execute',
  'jobs.read',
  'jobs.execute',
  'workflows.read',
  'workflows.create',
  'workflows.update',
  'workflows.execute',
  'rules.read',
  'reports.read',
  'reports.create',
  'reports.execute',
  'reports.export',
  'dashboards.read',
  'dashboards.create',
  'incidents.read',
  'incidents.create',
  'analytics.read',
  'analytics.export',
] as const;

const TEACHER_MANAGER: readonly Permission[] = [
  'users.read',
  'users.export',
  'moodles.read',
  'courses.read',
  'courses.create',
  'courses.update',
  'courses.export',
  'categories.read',
  'enrolments.read',
  'enrolments.export',
  'cohorts.read',
  'groups.read',
  'activities.read',
  'grades.read',
  'grades.export',
  'completion.read',
  'completion.export',
  'templates.read',
  'periods.read',
  'plans.read',
  'plans.create',
  'plans.execute',
  'jobs.read',
  'reports.read',
  'reports.execute',
  'reports.export',
  'dashboards.read',
  'incidents.read',
  'incidents.create',
  'analytics.read',
  'analytics.export',
] as const;

const HELP_DESK: readonly Permission[] = [
  'users.read',
  'users.update',
  'moodles.read',
  'courses.read',
  'categories.read',
  'enrolments.read',
  'enrolments.create',
  'enrolments.execute',
  'cohorts.read',
  'groups.read',
  'activities.read',
  'grades.read',
  'completion.read',
  'jobs.read',
  'incidents.read',
  'incidents.create',
  'incidents.update',
  'incidents.delete',
  'incidents.manage',
  'notifications.read',
  'notifications.update',
  'analytics.read',
] as const;

const ANALYST: readonly Permission[] = [
  'users.read',
  'users.export',
  'moodles.read',
  'courses.read',
  'courses.export',
  'categories.read',
  'categories.export',
  'enrolments.read',
  'enrolments.export',
  'cohorts.read',
  'cohorts.export',
  'groups.read',
  'groups.export',
  'activities.read',
  'grades.read',
  'grades.export',
  'completion.read',
  'completion.export',
  'periods.read',
  'templates.read',
  'reports.read',
  'reports.create',
  'reports.update',
  'reports.delete',
  'reports.execute',
  'reports.export',
  'dashboards.read',
  'dashboards.create',
  'dashboards.update',
  'dashboards.delete',
  'dashboards.manage',
  'incidents.read',
  'audit.read',
  'analytics.read',
  'analytics.export',
] as const;

const AUDITOR: readonly string[] = [
  'users.read',
  'users.export',
  'moodles.read',
  'courses.read',
  'courses.export',
  'categories.read',
  'categories.export',
  'enrolments.read',
  'enrolments.export',
  'cohorts.read',
  'cohorts.export',
  'groups.read',
  'groups.export',
  'activities.read',
  'grades.read',
  'grades.export',
  'completion.read',
  'completion.export',
  'periods.read',
  'templates.read',
  'plans.read',
  'jobs.read',
  'workflows.read',
  'rules.read',
  'reports.read',
  'reports.execute',
  'reports.export',
  'dashboards.read',
  'incidents.read',
  'audit.read',
  'audit.export',
  'analytics.read',
  'analytics.export',
  'apiKeys.read',
  'integrations.read',
  // Auditor must not be able to mutate academic data, even transiently.
  '-users.update',
  '-users.create',
  '-users.delete',
  '-courses.create',
  '-courses.update',
  '-courses.delete',
  '-enrolments.create',
  '-enrolments.delete',
  '-plans.create',
  '-plans.execute',
  '-jobs.execute',
] as const;

const VIEWER: readonly string[] = [
  'users.read',
  'moodles.read',
  'courses.read',
  'categories.read',
  'enrolments.read',
  'cohorts.read',
  'groups.read',
  'activities.read',
  'grades.read',
  'completion.read',
  'periods.read',
  'reports.read',
  'dashboards.read',
  'incidents.read',
  'analytics.read',
  '-audit.read',
] as const;

/**
 * Role -> permissions, including the shared tenant baseline. Deny entries are
 * listed explicitly where they matter so the intent is readable.
 */
export const ROLE_PERMISSIONS: Record<Role, readonly string[]> = {
  super_admin: [...TENANT_BASELINE, ...SUPER_ADMIN],
  tenant_admin: [...TENANT_BASELINE, ...TENANT_ADMIN],
  moodle_admin: [...TENANT_BASELINE, ...MOODLE_ADMIN],
  academic_coordinator: [...TENANT_BASELINE, ...ACADEMIC_COORDINATOR],
  teacher_manager: [...TENANT_BASELINE, ...TEACHER_MANAGER],
  help_desk: [...TENANT_BASELINE, ...HELP_DESK],
  analyst: [...TENANT_BASELINE, ...ANALYST],
  auditor: [...TENANT_BASELINE, ...AUDITOR],
  viewer: [...TENANT_BASELINE, ...VIEWER],
};